steps:
# Step 1: Build the Docker image using the Dockerfile
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple-app:$COMMIT_SHA', '.']

# Step 2: Push the Docker image to Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/simple-app:$COMMIT_SHA']

# Step 3: Deploy the Docker image to Kubernetes (optional)
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'k8s/deployment.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'

images:
- 'gcr.io/$PROJECT_ID/simple-app:$COMMIT_SHA'